version: '2'
services:
    databaseindicatori-app:
        image: databaseindicatori
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://databaseindicatori-postgresql:5432/DatabaseIndicatori
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=databaseindicatori-elasticsearch:9300
        ports:
            - 8080:8080
    databaseindicatori-postgresql:
        extends:
            file: postgresql.yml
            service: databaseindicatori-postgresql
    databaseindicatori-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: databaseindicatori-elasticsearch
